# Generated by Django 5.2.4 on 2025-12-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotificationAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sent',
            new_name='seen',
        ),
    ]
