# Generated by Django 5.2.4 on 2025-12-19 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0006_product_provider'),
        ('NotificationAPI', '0002_rename_sent_notification_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('STOCK', 'Stock'), ('EXP', 'Vencimiento'), ('NO_STOCK', 'Cero stock')], max_length=10)),
                ('text', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventoryAPI.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
