# Generated by Django 5.2.4 on 2026-02-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0007_alter_offer_options_alter_offer_created_at_and_more'),
        ('NotificationAPI', '0003_productnotification_delete_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productnotification',
            options={'verbose_name': 'notificación de producto', 'verbose_name_plural': 'notificaciones de productos'},
        ),
        migrations.AlterField(
            model_name='productnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='productnotification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventoryAPI.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productnotification',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='visto'),
        ),
        migrations.AlterField(
            model_name='productnotification',
            name='subject',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('EXP', 'Vencimiento'), ('NO_STOCK', 'Cero stock')], max_length=10, verbose_name='sujeto'),
        ),
        migrations.AlterField(
            model_name='productnotification',
            name='text',
            field=models.TextField(verbose_name='texto'),
        ),
    ]
