# Generated by Django 5.2.4 on 2026-02-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
    ]
