# Generated by Django 5.2.4 on 2025-08-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='initial_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price_iva',
            field=models.FloatField(default=0),
        ),
    ]
