# Generated by Django 5.2.4 on 2025-08-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAPI', '0002_sale_initial_price_alter_sale_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_price_iva',
        ),
    ]
