# Generated by Django 5.2.4 on 2025-12-10 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAPI', '0003_remove_sale_total_price_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tax_percentage',
        ),
    ]
