# Generated by Django 5.2.4 on 2025-12-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAPI', '0004_remove_sale_tax_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='applied_discount_percentage',
            new_name='applied_charge_percentage',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='discount_reason',
            new_name='charge_reason',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='discount_percentage',
            new_name='charge_percentage',
        ),
    ]
