# Generated by Django 5.2.4 on 2025-12-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayMethodAPI', '0001_initial'),
        ('SalesAPI', '0005_rename_applied_discount_percentage_sale_applied_charge_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pay_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PayMethodAPI.paymethod'),
        ),
    ]
