# Generated by Django 5.2.4 on 2025-12-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAPI', '0006_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
