# Generated by Django 5.2.4 on 2025-12-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAPI', '0007_alter_sale_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
