# Generated by Django 5.2.4 on 2026-01-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAPI', '0008_alter_sale_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
