# Generated by Django 5.2.4 on 2026-02-03 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0007_alter_offer_options_alter_offer_created_at_and_more'),
        ('PaymentMethodAPI', '0003_alter_paymentmethod_options_alter_paymentmethod_name'),
        ('SalesAPI', '0009_alter_saleitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'detalle de venta', 'verbose_name_plural': 'detalles de ventas'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='applied_charge_percentage',
            field=models.FloatField(default=0, verbose_name='porcentaje extra aplicado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='charge_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='razón del porcentaje extra aplicado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='initial_price',
            field=models.FloatField(default=0, verbose_name='precio inicial'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PaymentMethodAPI.paymentmethod', verbose_name='método de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='precio total'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='charge_percentage',
            field=models.FloatField(default=0, verbose_name='porcentaje extra'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InventoryAPI.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='SalesAPI.sale', verbose_name='venta'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.FloatField(verbose_name='precio unitario'),
        ),
    ]
