name: Build Installer

on:
  push:
    branches: [main]

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t backendimage ./Backend
          docker build -t frontendimage ./Frontend

      - name: Export images
        run: |
          docker save backendimage -o backend.tar
          docker save frontendimage -o frontend.tar

      - name: Prepare dist folder
        run: |
          mkdir dist
          mkdir dist\images
          copy backend.tar dist\images\
          copy frontend.tar dist\images\
          copy scripts\run.bat dist\

      - name: Download Podman portable
        run: |
          curl -L -o podman.zip https://github.com/containers/podman/releases/latest/download/podman-windows.zip
          powershell Expand-Archive podman.zip -DestinationPath dist/podman

      - name: Install NSIS
        uses: joncloud/makensis-action@v3
        with:
          script-path: installer.nsi

      - name: Rename Installer
        run: move MiAppSetup.exe dist\MiAppSetup.exe

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/MiAppSetup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
