# Generated by Django 5.2.4 on 2025-07-26 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProvidersAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('stock', models.IntegerField()),
                ('sell_price', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('last_modification', models.DateField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProvidersAPI.provider')),
            ],
        ),
    ]
