# Generated by Django 5.2.4 on 2025-07-30 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0001_initial'),
        ('ProvidersAPI', '0003_provider_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProvidersAPI.provider'),
        ),
    ]
