# Generated by Django 5.2.4 on 2025-08-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.FloatField(),
        ),
    ]
