# Generated by Django 5.2.4 on 2025-12-14 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryAPI', '0001_initial'),
        ('InventoryAPI', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CategoryAPI.category'),
        ),
    ]
