# Generated by Django 5.2.4 on 2025-07-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0002_alter_product_provider'),
        ('InventoryAPI', '0002_alter_product_provider_offer'),
    ]

    operations = [
    ]
