# Generated by Django 5.2.4 on 2025-12-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
