# Generated by Django 5.2.4 on 2026-01-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0004_product_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
