# Generated by Django 5.2.4 on 2025-12-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0004_product_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
    ]
