# Generated by Django 5.2.4 on 2026-02-03 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryAPI', '0001_initial'),
        ('InventoryAPI', '0005_product_in_use'),
        ('ProvidersAPI', '0005_alter_provider_address_alter_provider_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_price',
            field=models.FloatField(verbose_name='precio de compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CategoryAPI.category', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration',
            field=models.DateField(blank=True, null=True, verbose_name='vencimiento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_use',
            field=models.BooleanField(default=True, verbose_name='en uso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modification',
            field=models.DateField(auto_now_add=True, verbose_name='última modificación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProvidersAPI.provider', verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(verbose_name='precio de venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.FloatField(verbose_name='stock'),
        ),
    ]
