# Generated by Django 5.2.4 on 2025-12-18 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0005_remove_product_provider'),
        ('ProvidersAPI', '0007_remove_provider_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProvidersAPI.provider'),
        ),
    ]
