# Generated by Django 5.2.4 on 2026-02-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0006_alter_product_options_alter_product_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'oferta', 'verbose_name_plural': 'ofertas'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(verbose_name='fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='percentage',
            field=models.FloatField(verbose_name='porcentaje'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(related_name='offers', to='InventoryAPI.product', verbose_name='productos'),
        ),
    ]
