# Generated by Django 5.2.4 on 2026-02-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0007_alter_offer_options_alter_offer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_de_nuevo',
            field=models.BooleanField(default=True, verbose_name='test'),
        ),
    ]
