# Generated by Django 5.2.4 on 2026-02-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0007_alter_offer_options_alter_offer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='es_test',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
