# Generated by Django 5.2.4 on 2026-02-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0008_product_test_de_nuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test_de_nuevo',
        ),
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
