# Generated by Django 5.2.4 on 2026-02-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0008_product_es_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='es_test_dos',
            field=models.IntegerField(default=11, null=True),
        ),
    ]
