# Generated by Django 5.2.4 on 2026-02-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0009_remove_product_test_de_nuevo_product_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test',
        ),
    ]
