# Generated by Django 5.2.4 on 2026-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain', models.FloatField(blank=True, default=0, null=True, verbose_name='ganancia')),
                ('loss', models.FloatField(blank=True, default=0, null=True, verbose_name='perdida')),
                ('created_at', models.DateField(auto_now_add=True, unique=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'Reporte financiero',
                'verbose_name_plural': 'reportes financieros diarios',
            },
        ),
    ]
