# Generated by Django 5.2.4 on 2026-02-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReportAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ganancia'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='perdida'),
        ),
    ]
