# Generated by Django 5.2.4 on 2025-12-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentMethodAPI', '0001_initial'),
        ('SalesAPI', '0005_rename_applied_discount_percentage_sale_applied_charge_percentage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayMethod',
            new_name='PaymentMethod',
        ),
    ]
