# Generated by Django 5.2.4 on 2026-02-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentMethodAPI', '0002_rename_paymethod_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'método de pago', 'verbose_name_plural': 'metodos de pago'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='nombre'),
        ),
    ]
