# Generated by Django 5.2.4 on 2025-08-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlameAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='object_id',
            field=models.TextField(),
        ),
    ]
