# Generated by Django 5.2.4 on 2026-02-03 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlameAPI', '0003_alter_changelog_changed_at_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['-changed_at'], 'verbose_name': 'registro de cambios', 'verbose_name_plural': 'registros de cambios'},
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cambiado por'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo de contenido'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='field_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre del campo'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='nuevo valor'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='object_id',
            field=models.TextField(verbose_name='id del objeto'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='valor anterior'),
        ),
    ]
