# Generated by Django 5.2.4 on 2026-01-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydetail',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
