# Generated by Django 5.2.4 on 2026-01-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0002_entrydetail_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
