# Generated by Django 5.2.4 on 2026-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0003_entry_total_entrydetail_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydetail',
            name='receipt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
