# Generated by Django 5.2.4 on 2026-01-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0004_entrydetail_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrydetail',
            old_name='discount_percentage',
            new_name='surcharge_percentage',
        ),
    ]
