# Generated by Django 5.2.4 on 2026-01-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0005_rename_discount_percentage_entrydetail_surcharge_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrydetail',
            old_name='stock_amount',
            new_name='extra_percentage',
        ),
        migrations.RemoveField(
            model_name='entrydetail',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='entrydetail',
            name='surcharge_percentage',
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='observations',
            field=models.TextField(blank=True, default='Sin observaciones', null=True),
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='unit_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
