# Generated by Django 5.2.4 on 2026-01-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0006_rename_stock_amount_entrydetail_extra_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydetail',
            name='receipt',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
    ]
