# Generated by Django 5.2.4 on 2026-02-03 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0007_alter_entrydetail_receipt'),
        ('InventoryAPI', '0007_alter_offer_options_alter_offer_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'ingreso', 'verbose_name_plural': 'ingresos'},
        ),
        migrations.AlterModelOptions(
            name='entrydetail',
            options={'verbose_name': 'detalle de ingreso', 'verbose_name_plural': 'detalles de ingreso'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='total',
            field=models.FloatField(default=0, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='EntryAPI.entry', verbose_name='ingreso'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='extra_percentage',
            field=models.FloatField(default=0, verbose_name='porcentaje extra'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='observations',
            field=models.TextField(blank=True, default='Sin observaciones', null=True, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InventoryAPI.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='quantity',
            field=models.FloatField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='receipt',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='recibo'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='unit_price',
            field=models.FloatField(verbose_name='precio unitario'),
        ),
    ]
