# Generated by Django 5.2.4 on 2026-02-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0008_alter_entry_options_alter_entrydetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrydetail',
            name='extra_percentage',
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='applied_charge',
            field=models.FloatField(default=0, verbose_name='cargo extra'),
        ),
    ]
