# Generated by Django 5.2.4 on 2026-02-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0009_remove_entrydetail_extra_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrydetail',
            name='receipt',
        ),
        migrations.AddField(
            model_name='entry',
            name='rute_number',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='numero de ruta'),
        ),
    ]
