# Generated by Django 5.2.4 on 2026-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0010_remove_entrydetail_receipt_entry_rute_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrydetail',
            name='observations',
        ),
        migrations.AddField(
            model_name='entry',
            name='observations',
            field=models.TextField(blank=True, default='Sin observaciones', null=True, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rute_number',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='numero de remito'),
        ),
    ]
