# Generated by Django 5.2.4 on 2026-02-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0010_remove_entrydetail_receipt_entry_rute_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rute_number',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='numero de remito'),
        ),
    ]
