# Generated by Django 5.2.4 on 2026-02-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntryAPI', '0011_alter_entry_rute_number'),
        ('EntryAPI', '0011_remove_entrydetail_observations_entry_observations_and_more'),
    ]

    operations = [
    ]
