# Generated by Django 5.2.4 on 2025-07-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
