# Generated by Django 5.2.4 on 2025-11-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_custompermission_alter_role_name_sp_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('salesperson', 'Vendedor'), ('stocker', 'Repositor'), ('administrator', 'Administrador'), ('salesperson_stocker', 'Vendedor y repositor')], max_length=20, unique=True),
        ),
    ]
