# Generated by Django 5.2.4 on 2026-01-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='askForPin',
            field=models.BooleanField(default=True),
        ),
    ]
