# Generated by Django 5.2.4 on 2026-02-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_customuser_askforpin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='askForPin',
            field=models.BooleanField(default=True, verbose_name='pedir pin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='está activo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='es staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.CharField(max_length=5, verbose_name='pin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.role', verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('salesperson', 'Vendedor'), ('stocker', 'Repositor'), ('administrator', 'Administrador'), ('salesperson_stocker', 'Vendedor y repositor')], max_length=20, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name_sp',
            field=models.CharField(max_length=20, unique=True, verbose_name='nombre_esp'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='Auth.custompermission', verbose_name='permisos'),
        ),
    ]
