# Generated by Django 5.2.4 on 2026-02-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_customuser_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_to_decide_stock_decrease',
            field=models.BooleanField(default=True, verbose_name='puede decidir si la disminucion de stock genera perdidas'),
        ),
    ]
