# Generated by Django 5.2.4 on 2026-02-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_customuser_allowed_to_decide_stock_decrease'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='create_loss_when_product_delete',
            field=models.BooleanField(default=True, verbose_name='genera perdidas cuando se eliminan productos'),
        ),
    ]
