# Generated by Django 5.2.4 on 2025-07-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProvidersAPI', '0002_provider_address_provider_created_at_provider_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
    ]
