# Generated by Django 5.2.4 on 2025-08-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProvidersAPI', '0003_provider_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, default='Sin dirección', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, default='00000', max_length=20, null=True),
        ),
    ]
