# Generated by Django 5.2.4 on 2025-08-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProvidersAPI', '0004_alter_provider_address_alter_provider_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(
                blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(
                blank=True, default='', max_length=20, null=True),
        ),
    ]
