# Generated by Django 5.2.4 on 2026-02-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProvidersAPI', '0005_alter_provider_address_alter_provider_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
    ]
