# Generated by Django 5.2.4 on 2025-12-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0005_remove_product_provider'),
        ('ProvidersAPI', '0005_alter_provider_address_alter_provider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='providers', to='InventoryAPI.product'),
        ),
    ]
