# Generated by Django 5.2.4 on 2025-12-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProvidersAPI', '0006_provider_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='products',
        ),
    ]
